GARNAME = tcl
GARVERSION = 8.4
CATEGORIES = main

LIBDEPS = tcl/tcl \
          tcl/tk \
	  tcl/itcl \
          tcl/tcllib \
          tcl/tclreadline \
	  tcl/tls \
	  tcl/tclcurl \
	  tcl/oratcl \
	  tcl/tdom \
	  tcl/snack \
	  tcl/bwidgets \
	  tcl/iwidgets \
          tcl/tktable \
	  tcl/tablelist \
	  tcl/expect \
	  tcl/tkcon

DESCRIPTION = tcl
define BLURB
 #FIXME: blurb goes here
endef

include ../../gar.mk

